/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQrScanRouteImport } from './routes/_authenticated/qr-scan'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedFaultsRouteImport } from './routes/_authenticated/faults'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTransformersIndexRouteImport } from './routes/_authenticated/transformers/index'
import { Route as AuthenticatedTransformersNewRouteImport } from './routes/_authenticated/transformers/new'
import { Route as AuthenticatedTransformersIdRouteImport } from './routes/_authenticated/transformers/$id'
import { Route as AuthenticatedMaintenanceNewRouteImport } from './routes/_authenticated/maintenance.new'
import { Route as AuthenticatedInspectionsNewRouteImport } from './routes/_authenticated/inspections.new'
import { Route as AuthenticatedFaultsNewRouteImport } from './routes/_authenticated/faults.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQrScanRoute = AuthenticatedQrScanRouteImport.update({
  id: '/qr-scan',
  path: '/qr-scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaultsRoute = AuthenticatedFaultsRouteImport.update({
  id: '/faults',
  path: '/faults',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransformersIndexRoute =
  AuthenticatedTransformersIndexRouteImport.update({
    id: '/transformers/',
    path: '/transformers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransformersNewRoute =
  AuthenticatedTransformersNewRouteImport.update({
    id: '/transformers/new',
    path: '/transformers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransformersIdRoute =
  AuthenticatedTransformersIdRouteImport.update({
    id: '/transformers/$id',
    path: '/transformers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceNewRoute =
  AuthenticatedMaintenanceNewRouteImport.update({
    id: '/maintenance/new',
    path: '/maintenance/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionsNewRoute =
  AuthenticatedInspectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInspectionsRoute,
  } as any)
const AuthenticatedFaultsNewRoute = AuthenticatedFaultsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedFaultsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faults': typeof AuthenticatedFaultsRouteWithChildren
  '/inspections': typeof AuthenticatedInspectionsRouteWithChildren
  '/map': typeof AuthenticatedMapRoute
  '/qr-scan': typeof AuthenticatedQrScanRoute
  '/faults/new': typeof AuthenticatedFaultsNewRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/transformers/$id': typeof AuthenticatedTransformersIdRoute
  '/transformers/new': typeof AuthenticatedTransformersNewRoute
  '/transformers/': typeof AuthenticatedTransformersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faults': typeof AuthenticatedFaultsRouteWithChildren
  '/inspections': typeof AuthenticatedInspectionsRouteWithChildren
  '/map': typeof AuthenticatedMapRoute
  '/qr-scan': typeof AuthenticatedQrScanRoute
  '/faults/new': typeof AuthenticatedFaultsNewRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/transformers/$id': typeof AuthenticatedTransformersIdRoute
  '/transformers/new': typeof AuthenticatedTransformersNewRoute
  '/transformers': typeof AuthenticatedTransformersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faults': typeof AuthenticatedFaultsRouteWithChildren
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRouteWithChildren
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/qr-scan': typeof AuthenticatedQrScanRoute
  '/_authenticated/faults/new': typeof AuthenticatedFaultsNewRoute
  '/_authenticated/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/_authenticated/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/_authenticated/transformers/$id': typeof AuthenticatedTransformersIdRoute
  '/_authenticated/transformers/new': typeof AuthenticatedTransformersNewRoute
  '/_authenticated/transformers/': typeof AuthenticatedTransformersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/faults'
    | '/inspections'
    | '/map'
    | '/qr-scan'
    | '/faults/new'
    | '/inspections/new'
    | '/maintenance/new'
    | '/transformers/$id'
    | '/transformers/new'
    | '/transformers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/faults'
    | '/inspections'
    | '/map'
    | '/qr-scan'
    | '/faults/new'
    | '/inspections/new'
    | '/maintenance/new'
    | '/transformers/$id'
    | '/transformers/new'
    | '/transformers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/faults'
    | '/_authenticated/inspections'
    | '/_authenticated/map'
    | '/_authenticated/qr-scan'
    | '/_authenticated/faults/new'
    | '/_authenticated/inspections/new'
    | '/_authenticated/maintenance/new'
    | '/_authenticated/transformers/$id'
    | '/_authenticated/transformers/new'
    | '/_authenticated/transformers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/qr-scan': {
      id: '/_authenticated/qr-scan'
      path: '/qr-scan'
      fullPath: '/qr-scan'
      preLoaderRoute: typeof AuthenticatedQrScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faults': {
      id: '/_authenticated/faults'
      path: '/faults'
      fullPath: '/faults'
      preLoaderRoute: typeof AuthenticatedFaultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transformers/': {
      id: '/_authenticated/transformers/'
      path: '/transformers'
      fullPath: '/transformers/'
      preLoaderRoute: typeof AuthenticatedTransformersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transformers/new': {
      id: '/_authenticated/transformers/new'
      path: '/transformers/new'
      fullPath: '/transformers/new'
      preLoaderRoute: typeof AuthenticatedTransformersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transformers/$id': {
      id: '/_authenticated/transformers/$id'
      path: '/transformers/$id'
      fullPath: '/transformers/$id'
      preLoaderRoute: typeof AuthenticatedTransformersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/new': {
      id: '/_authenticated/maintenance/new'
      path: '/maintenance/new'
      fullPath: '/maintenance/new'
      preLoaderRoute: typeof AuthenticatedMaintenanceNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections/new': {
      id: '/_authenticated/inspections/new'
      path: '/new'
      fullPath: '/inspections/new'
      preLoaderRoute: typeof AuthenticatedInspectionsNewRouteImport
      parentRoute: typeof AuthenticatedInspectionsRoute
    }
    '/_authenticated/faults/new': {
      id: '/_authenticated/faults/new'
      path: '/new'
      fullPath: '/faults/new'
      preLoaderRoute: typeof AuthenticatedFaultsNewRouteImport
      parentRoute: typeof AuthenticatedFaultsRoute
    }
  }
}

interface AuthenticatedFaultsRouteChildren {
  AuthenticatedFaultsNewRoute: typeof AuthenticatedFaultsNewRoute
}

const AuthenticatedFaultsRouteChildren: AuthenticatedFaultsRouteChildren = {
  AuthenticatedFaultsNewRoute: AuthenticatedFaultsNewRoute,
}

const AuthenticatedFaultsRouteWithChildren =
  AuthenticatedFaultsRoute._addFileChildren(AuthenticatedFaultsRouteChildren)

interface AuthenticatedInspectionsRouteChildren {
  AuthenticatedInspectionsNewRoute: typeof AuthenticatedInspectionsNewRoute
}

const AuthenticatedInspectionsRouteChildren: AuthenticatedInspectionsRouteChildren =
  {
    AuthenticatedInspectionsNewRoute: AuthenticatedInspectionsNewRoute,
  }

const AuthenticatedInspectionsRouteWithChildren =
  AuthenticatedInspectionsRoute._addFileChildren(
    AuthenticatedInspectionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaultsRoute: typeof AuthenticatedFaultsRouteWithChildren
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRouteWithChildren
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedQrScanRoute: typeof AuthenticatedQrScanRoute
  AuthenticatedMaintenanceNewRoute: typeof AuthenticatedMaintenanceNewRoute
  AuthenticatedTransformersIdRoute: typeof AuthenticatedTransformersIdRoute
  AuthenticatedTransformersNewRoute: typeof AuthenticatedTransformersNewRoute
  AuthenticatedTransformersIndexRoute: typeof AuthenticatedTransformersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaultsRoute: AuthenticatedFaultsRouteWithChildren,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRouteWithChildren,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedQrScanRoute: AuthenticatedQrScanRoute,
  AuthenticatedMaintenanceNewRoute: AuthenticatedMaintenanceNewRoute,
  AuthenticatedTransformersIdRoute: AuthenticatedTransformersIdRoute,
  AuthenticatedTransformersNewRoute: AuthenticatedTransformersNewRoute,
  AuthenticatedTransformersIndexRoute: AuthenticatedTransformersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
