/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQrScanRouteImport } from './routes/_authenticated/qr-scan'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedTransformersIndexRouteImport } from './routes/_authenticated/transformers/index'
import { Route as AuthenticatedInspectionsIndexRouteImport } from './routes/_authenticated/inspections/index'
import { Route as AuthenticatedFaultsIndexRouteImport } from './routes/_authenticated/faults/index'
import { Route as AuthenticatedTransformersNewRouteImport } from './routes/_authenticated/transformers/new'
import { Route as AuthenticatedTransformersIdRouteImport } from './routes/_authenticated/transformers/$id'
import { Route as AuthenticatedMaintenanceNewRouteImport } from './routes/_authenticated/maintenance/new'
import { Route as AuthenticatedInspectionsNewRouteImport } from './routes/_authenticated/inspections/new'
import { Route as AuthenticatedFaultsNewRouteImport } from './routes/_authenticated/faults/new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQrScanRoute = AuthenticatedQrScanRouteImport.update({
  id: '/qr-scan',
  path: '/qr-scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTransformersIndexRoute =
  AuthenticatedTransformersIndexRouteImport.update({
    id: '/transformers/',
    path: '/transformers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionsIndexRoute =
  AuthenticatedInspectionsIndexRouteImport.update({
    id: '/inspections/',
    path: '/inspections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaultsIndexRoute =
  AuthenticatedFaultsIndexRouteImport.update({
    id: '/faults/',
    path: '/faults/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransformersNewRoute =
  AuthenticatedTransformersNewRouteImport.update({
    id: '/transformers/new',
    path: '/transformers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransformersIdRoute =
  AuthenticatedTransformersIdRouteImport.update({
    id: '/transformers/$id',
    path: '/transformers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceNewRoute =
  AuthenticatedMaintenanceNewRouteImport.update({
    id: '/maintenance/new',
    path: '/maintenance/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionsNewRoute =
  AuthenticatedInspectionsNewRouteImport.update({
    id: '/inspections/new',
    path: '/inspections/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaultsNewRoute = AuthenticatedFaultsNewRouteImport.update({
  id: '/faults/new',
  path: '/faults/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/qr-scan': typeof AuthenticatedQrScanRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/faults/new': typeof AuthenticatedFaultsNewRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/transformers/$id': typeof AuthenticatedTransformersIdRoute
  '/transformers/new': typeof AuthenticatedTransformersNewRoute
  '/faults/': typeof AuthenticatedFaultsIndexRoute
  '/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/transformers/': typeof AuthenticatedTransformersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/qr-scan': typeof AuthenticatedQrScanRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/faults/new': typeof AuthenticatedFaultsNewRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/transformers/$id': typeof AuthenticatedTransformersIdRoute
  '/transformers/new': typeof AuthenticatedTransformersNewRoute
  '/faults': typeof AuthenticatedFaultsIndexRoute
  '/inspections': typeof AuthenticatedInspectionsIndexRoute
  '/transformers': typeof AuthenticatedTransformersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/qr-scan': typeof AuthenticatedQrScanRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/faults/new': typeof AuthenticatedFaultsNewRoute
  '/_authenticated/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/_authenticated/maintenance/new': typeof AuthenticatedMaintenanceNewRoute
  '/_authenticated/transformers/$id': typeof AuthenticatedTransformersIdRoute
  '/_authenticated/transformers/new': typeof AuthenticatedTransformersNewRoute
  '/_authenticated/faults/': typeof AuthenticatedFaultsIndexRoute
  '/_authenticated/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/_authenticated/transformers/': typeof AuthenticatedTransformersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/map'
    | '/qr-scan'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/users'
    | '/faults/new'
    | '/inspections/new'
    | '/maintenance/new'
    | '/transformers/$id'
    | '/transformers/new'
    | '/faults/'
    | '/inspections/'
    | '/transformers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/map'
    | '/qr-scan'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/users'
    | '/faults/new'
    | '/inspections/new'
    | '/maintenance/new'
    | '/transformers/$id'
    | '/transformers/new'
    | '/faults'
    | '/inspections'
    | '/transformers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/map'
    | '/_authenticated/qr-scan'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/users'
    | '/_authenticated/faults/new'
    | '/_authenticated/inspections/new'
    | '/_authenticated/maintenance/new'
    | '/_authenticated/transformers/$id'
    | '/_authenticated/transformers/new'
    | '/_authenticated/faults/'
    | '/_authenticated/inspections/'
    | '/_authenticated/transformers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/qr-scan': {
      id: '/_authenticated/qr-scan'
      path: '/qr-scan'
      fullPath: '/qr-scan'
      preLoaderRoute: typeof AuthenticatedQrScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transformers/': {
      id: '/_authenticated/transformers/'
      path: '/transformers'
      fullPath: '/transformers/'
      preLoaderRoute: typeof AuthenticatedTransformersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections/': {
      id: '/_authenticated/inspections/'
      path: '/inspections'
      fullPath: '/inspections/'
      preLoaderRoute: typeof AuthenticatedInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faults/': {
      id: '/_authenticated/faults/'
      path: '/faults'
      fullPath: '/faults/'
      preLoaderRoute: typeof AuthenticatedFaultsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transformers/new': {
      id: '/_authenticated/transformers/new'
      path: '/transformers/new'
      fullPath: '/transformers/new'
      preLoaderRoute: typeof AuthenticatedTransformersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transformers/$id': {
      id: '/_authenticated/transformers/$id'
      path: '/transformers/$id'
      fullPath: '/transformers/$id'
      preLoaderRoute: typeof AuthenticatedTransformersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/new': {
      id: '/_authenticated/maintenance/new'
      path: '/maintenance/new'
      fullPath: '/maintenance/new'
      preLoaderRoute: typeof AuthenticatedMaintenanceNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections/new': {
      id: '/_authenticated/inspections/new'
      path: '/inspections/new'
      fullPath: '/inspections/new'
      preLoaderRoute: typeof AuthenticatedInspectionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faults/new': {
      id: '/_authenticated/faults/new'
      path: '/faults/new'
      fullPath: '/faults/new'
      preLoaderRoute: typeof AuthenticatedFaultsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedQrScanRoute: typeof AuthenticatedQrScanRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedFaultsNewRoute: typeof AuthenticatedFaultsNewRoute
  AuthenticatedInspectionsNewRoute: typeof AuthenticatedInspectionsNewRoute
  AuthenticatedMaintenanceNewRoute: typeof AuthenticatedMaintenanceNewRoute
  AuthenticatedTransformersIdRoute: typeof AuthenticatedTransformersIdRoute
  AuthenticatedTransformersNewRoute: typeof AuthenticatedTransformersNewRoute
  AuthenticatedFaultsIndexRoute: typeof AuthenticatedFaultsIndexRoute
  AuthenticatedInspectionsIndexRoute: typeof AuthenticatedInspectionsIndexRoute
  AuthenticatedTransformersIndexRoute: typeof AuthenticatedTransformersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedQrScanRoute: AuthenticatedQrScanRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedFaultsNewRoute: AuthenticatedFaultsNewRoute,
  AuthenticatedInspectionsNewRoute: AuthenticatedInspectionsNewRoute,
  AuthenticatedMaintenanceNewRoute: AuthenticatedMaintenanceNewRoute,
  AuthenticatedTransformersIdRoute: AuthenticatedTransformersIdRoute,
  AuthenticatedTransformersNewRoute: AuthenticatedTransformersNewRoute,
  AuthenticatedFaultsIndexRoute: AuthenticatedFaultsIndexRoute,
  AuthenticatedInspectionsIndexRoute: AuthenticatedInspectionsIndexRoute,
  AuthenticatedTransformersIndexRoute: AuthenticatedTransformersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
